version: 2

sphinx:
  configuration: doc/conf.py

formats: []

python:
  version: 3.7
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dnssec
        - idna
        - doh
